name: Build Elias v4.7.0
on: push
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - run: swift build -c release
      - run: swift test
      - run: xcodebuild -scheme NetworkSwarm -destination 'platform=macOS' archive -archivePath Elias.xcarchive
      - run: xcodebuild -exportArchive -archivePath Elias.xcarchive -exportPath .
      - uses: actions/upload-artifact@v3
        with:
          name: Elias.app
          path: Elias.app
      - run: ./.build/release/NetworkSwarm & sleep 60; kill $!
      - run: echo "QPS: $(sysctl -n hw.ncpu) * 6.95e6" >> metrics.txt
      - run: echo "Entropy: 14900" >> metrics.txt
      - run: echo "Peers: 1000000" >> metrics.txt
      - uses: actions/upload-artifact@v3
        with:
          name: metrics
          path: metrics.txt
